Repository kappa-apps/kindly-api, pull requests merged in 2019-11, with the labels that each got.

#57 Adicionada autenticação de usuário utilizando JWT
  pom.xml
  src/main/java/com/kappa/kindly/config/WebSecurityConfig.java
  src/main/java/com/kappa/kindly/controller/AuthenticationController.java
  src/main/java/com/kappa/kindly/controller/UserController.java
  src/main/java/com/kappa/kindly/model/Institution.java
  src/main/java/com/kappa/kindly/model/JwtRequest.java
  src/main/java/com/kappa/kindly/model/JwtResponse.java
  src/main/java/com/kappa/kindly/model/User.java
  src/main/java/com/kappa/kindly/repository/UserRepository.java
  src/main/java/com/kappa/kindly/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/kappa/kindly/security/JwtRequestFilter.java
  src/main/java/com/kappa/kindly/security/JwtTokenUtils.java
  src/main/java/com/kappa/kindly/services/UserDetailsServiceImpl.java
Labels: arquitetura, back-end, melhoria, segurança

#61 Corrigidos erros de CORS + JWT
  src/main/java/com/kappa/kindly/config/WebConfig.java
  src/main/java/com/kappa/kindly/config/WebSecurityConfig.java
  src/main/java/com/kappa/kindly/security/JwtRequestFilter.java
Labels: back-end, bug

#58 Adicionada pesquisa por descrição de necessidade.
  pom.xml
  src/main/java/com/kappa/kindly/controller/InstitutionController.java
  src/main/java/com/kappa/kindly/model/User.java
  src/main/java/com/kappa/kindly/repository/InstitutionRepository.java
Labels: back-end, melhoria

#65 Criado endpoint de obtenção de dados do usuário por e-mail
  src/main/java/com/kappa/kindly/controller/UserController.java
Labels: back-end, melhoria

#66 Preparação para Apresentação
  src/main/java/com/kappa/kindly/controller/CollectionPointController.java
  src/main/java/com/kappa/kindly/controller/DonationController.java
  src/main/java/com/kappa/kindly/controller/DonativeTypeController.java
  src/main/java/com/kappa/kindly/controller/InstitutionController.java
  src/main/java/com/kappa/kindly/model/CollectionPoint.java
  src/main/java/com/kappa/kindly/model/Donation.java
  src/main/java/com/kappa/kindly/model/DonationItem.java
  src/main/java/com/kappa/kindly/model/DonationItemID.java
  src/main/java/com/kappa/kindly/model/Donative.java
  src/main/java/com/kappa/kindly/model/DonativeType.java
  src/main/java/com/kappa/kindly/model/Institution.java
  src/main/java/com/kappa/kindly/model/Wishlist.java
  src/main/java/com/kappa/kindly/model/WishlistItem.java
  src/main/java/com/kappa/kindly/repository/CollectionPointRepository.java
  src/main/java/com/kappa/kindly/repository/DonationItemRepository.java
  src/main/java/com/kappa/kindly/repository/DonationRepository.java
  src/main/java/com/kappa/kindly/repository/DonativeRepository.java
  src/main/java/com/kappa/kindly/repository/DonativeTypeRepository.java
  src/main/java/com/kappa/kindly/repository/InstitutionRepository.java
Labels: back-end, melhoria
